trigger:
  branches:
    include:
      - main

pool:
  name: SelfHostedPool


variables:
  TF_WORKING_DIR: "terraform"
  AWS_DEFAULT_REGION: "us-east-1"
  RUN_DESTROY: "false"

stages:
  - stage: Terraform_Apply
    displayName: "Terraform Apply Stage"
    jobs:
      - job: Apply
        displayName: "Terraform Apply"
        steps:
          - checkout: self

          - script: |
              terraform --version
            displayName: "Verify Terraform Installation"

          - script: |
              # Check if S3 bucket exists, create if not
              aws s3 ls s3://nti-finalproject-terraform-state || aws s3 mb s3://nti-finalproject-terraform-state --region us-east-1
              
              # Check if DynamoDB table exists, create if not
              aws dynamodb describe-table --table-name nti-finalproject-terraform-lock --region us-east-1 || \
              aws dynamodb create-table \
                --table-name nti-finalproject-terraform-lock \
                --attribute-definitions AttributeName=LockID,AttributeType=S \
                --key-schema AttributeName=LockID,KeyType=HASH \
                --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
                --region us-east-1
              
              cd $(TF_WORKING_DIR)
              terraform init
            displayName: "Setup Backend and Terraform Init"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform validate
            displayName: "Terraform Validate"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform plan -var-file=nonprod.tfvars
            displayName: "Terraform Plan"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform apply -var-file=nonprod.tfvars -auto-approve
            displayName: "Terraform Apply"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform output
            displayName: "Terraform Outputs"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: Terraform_Destroy
    displayName: "Terraform Destroy Stage (Manual)"
    dependsOn: Terraform_Apply
    condition: and(succeeded(), eq(variables['RUN_DESTROY'], 'true'))

    jobs:
      - job: Destroy
        displayName: "Terraform Destroy"
        steps:
          - checkout: self

          - script: |
              terraform --version
            displayName: "Verify Terraform Installation"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform init
            displayName: "Terraform Init (Destroy)"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform destroy -var-file=nonprod.tfvars -auto-approve
            displayName: "Terraform Destroy"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)