trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**
      - .azure-infra-pipeline.yaml

pool:
  name: SelfHostedPool
  demands:
    - agent.os -equals Linux

variables:
  TF_WORKING_DIR: "terraform"
  AWS_DEFAULT_REGION: "us-east-1"
  TF_STATE_BUCKET: "nti-finalproject-terraform-state"
  TF_LOCK_TABLE: "nti-finalproject-terraform-lock"
  RUN_DESTROY: "false"

stages:

# ================================
# Terraform Validate Stage
# ================================
- stage: Terraform_Validate
  displayName: "Terraform Validation Stage"
  jobs:
    - job: ValidateTerraform
      displayName: "Validate Infrastructure Code"
      timeoutInMinutes: 30
      cancelTimeoutInMinutes: 5

      workspace:
        clean: all

      steps:
        - checkout: self

        - script: |
            echo "====================================="
            echo " Agent Health Check"
            echo "====================================="
            echo "Agent Name: $(Agent.Name)"
            echo "Agent OS: $(Agent.OS)"
            echo "Build ID: $(Build.BuildId)"
            df -h
            free -h || true
          displayName: "Agent Health Check"

        - script: |
            echo "====================================="
            echo " Verify Tools"
            echo "====================================="
            aws --version
            terraform --version
            git --version
          displayName: "Verify Tools"

        - script: |
            set -e
            cd $(TF_WORKING_DIR)

            echo "====================================="
            echo " Terraform Format Check"
            echo "====================================="
            terraform fmt -check -recursive

            echo "====================================="
            echo " Terraform Init"
            echo "====================================="
            terraform init -reconfigure
          displayName: "Terraform Format & Init"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e
            cd $(TF_WORKING_DIR)

            echo "====================================="
            echo " Terraform Validate"
            echo "====================================="
            terraform validate
          displayName: "Terraform Validate"

        - script: |
            set -e
            cd $(TF_WORKING_DIR)

            echo "====================================="
            echo " Terraform Plan"
            echo "====================================="
            terraform plan -var-file=nonprod.tfvars -out=tfplan
          displayName: "Terraform Plan"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

# ================================
# Terraform Apply Stage
# ================================
- stage: Terraform_Apply
  displayName: "Terraform Apply Stage"
  dependsOn: Terraform_Validate
  condition: succeeded()
  jobs:
    - job: TerraformApply
      displayName: "Apply Infrastructure"
      timeoutInMinutes: 60
      cancelTimeoutInMinutes: 5

      workspace:
        clean: all

      steps:
        - checkout: self

        - script: |
            echo "====================================="
            echo " Validate AWS Credentials"
            echo "====================================="
            aws sts get-caller-identity
          displayName: "Validate AWS Credentials"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e
            echo "====================================="
            echo " Setup Backend Resources"
            echo "====================================="

            echo "Checking S3 bucket: $(TF_STATE_BUCKET)"
            if aws s3api head-bucket --bucket $(TF_STATE_BUCKET) 2>/dev/null; then
              echo "S3 bucket exists"
            else
              echo "Creating S3 bucket..."
              aws s3api create-bucket --bucket $(TF_STATE_BUCKET) --region $(AWS_DEFAULT_REGION)
              aws s3api put-bucket-versioning --bucket $(TF_STATE_BUCKET) --versioning-configuration Status=Enabled
            fi

            echo "Checking DynamoDB table: $(TF_LOCK_TABLE)"
            if aws dynamodb describe-table --table-name $(TF_LOCK_TABLE) --region $(AWS_DEFAULT_REGION) >/dev/null 2>&1; then
              echo "DynamoDB table exists"
            else
              echo "Creating DynamoDB table..."
              aws dynamodb create-table \
                --table-name $(TF_LOCK_TABLE) \
                --attribute-definitions AttributeName=LockID,AttributeType=S \
                --key-schema AttributeName=LockID,KeyType=HASH \
                --billing-mode PAY_PER_REQUEST \
                --region $(AWS_DEFAULT_REGION)

              echo "Waiting for DynamoDB table..."
              aws dynamodb wait table-exists --table-name $(TF_LOCK_TABLE) --region $(AWS_DEFAULT_REGION)
            fi
          displayName: "Setup Backend Resources"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e
            cd $(TF_WORKING_DIR)

            echo "====================================="
            echo " Terraform Apply"
            echo "====================================="
            terraform init -reconfigure
            terraform apply -var-file=nonprod.tfvars -auto-approve
          displayName: "Terraform Apply"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            cd $(TF_WORKING_DIR)
            echo "====================================="
            echo " Terraform Outputs"
            echo "====================================="
            terraform output
          displayName: "Terraform Outputs"

        - script: |
            cd $(TF_WORKING_DIR)
            echo "====================================="
            echo " Infrastructure Deployment Complete"
            echo "====================================="
            echo "VPC, Subnets, EKS Cluster, and IAM roles have been provisioned."
            echo "ECR repository is ready for container images."
          displayName: "Infrastructure Summary"

# ================================
# Terraform Destroy Stage (Optional)
# ================================
- stage: Terraform_Destroy
  displayName: "Terraform Destroy Stage"
  dependsOn: Terraform_Apply
  condition: and(succeeded(), eq(variables['RUN_DESTROY'], 'true'))
  jobs:
    - job: TerraformDestroy
      displayName: "Destroy Infrastructure"
      timeoutInMinutes: 60
      cancelTimeoutInMinutes: 5

      workspace:
        clean: all

      steps:
        - checkout: self

        - script: |
            set -e
            echo "====================================="
            echo " Terraform Destroy"
            echo "====================================="

            cd $(TF_WORKING_DIR)
            terraform init -reconfigure
            terraform destroy -var-file=nonprod.tfvars -auto-approve
          displayName: "Terraform Destroy"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
