trigger:
  branches:
    include:
      - main
  paths:
    include:
      - helm/vault/**
      - helm/sonarqube/**
      - helm/nexus/**
      - helm/nginx-ingress-controller/**
      - helm/*-ingress.yaml
      - .azure-platform-pipeline.yaml

pool:
  name: SelfHostedPool
  demands:
    - agent.os -equals Linux

variables:
  HELM_WORKING_DIR: "helm"
  AWS_DEFAULT_REGION: "us-east-1"
  CLUSTER_NAME: "nti-final-nonprod-eks"   # <<< خلي اسم الكلاستر ثابت هنا
  RUN_CLEANUP: "false"

stages:

# ================================
# Platform Deployment Stage
# ================================
- stage: Platform_Deploy
  displayName: "Platform Tools Deployment Stage"
  jobs:
    - job: PlatformDeployment
      displayName: "Deploy Platform Components"
      timeoutInMinutes: 120
      cancelTimeoutInMinutes: 5

      workspace:
        clean: all

      steps:
        - checkout: self

        - task: HelmInstaller@1
          displayName: "Install Helm"
          inputs:
            helmVersionToInstall: "latest"

        - task: KubectlInstaller@0
          displayName: "Install kubectl"
          inputs:
            kubectlVersion: "latest"

        # ================================
        # Validate AWS Credentials
        # ================================
        - script: |
            echo "====================================="
            echo " Validate AWS Credentials"
            echo "====================================="

            set -e
            aws --version

            echo "Testing AWS credentials..."
            aws sts get-caller-identity

            echo " AWS credentials are valid"
          displayName: "Validate AWS Credentials"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        # ================================
        # Configure kubeconfig
        # ================================
        - script: |
            echo "====================================="
            echo " Configure kubectl for EKS"
            echo "====================================="

            set -e

            echo "Cluster Name: $(CLUSTER_NAME)"
            mkdir -p $HOME/.kube

            aws eks update-kubeconfig \
              --region "$(AWS_DEFAULT_REGION)" \
              --name "$(CLUSTER_NAME)" \
              --kubeconfig "$HOME/.kube/config"

            export KUBECONFIG="$HOME/.kube/config"

            echo "Testing kubectl..."
            kubectl cluster-info
            kubectl get nodes -o wide
          displayName: "Configure kubectl for EKS"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        # ================================
        # Add Helm Repositories
        # ================================
        - script: |
            echo "====================================="
            echo " Add Helm Repositories"
            echo "====================================="

            set -e

            # Function to add or update Helm repository
            add_or_update_repo() {
              local repo_name=$1
              local repo_url=$2
              
              if helm repo list | grep -q "^$repo_name\s"; then
                echo "Repository '$repo_name' already exists, updating..."
                helm repo update $repo_name
              else
                echo "Adding repository '$repo_name'..."
                helm repo add $repo_name $repo_url
              fi
            }

            # Add/Update all required repositories
            add_or_update_repo hashicorp https://helm.releases.hashicorp.com
            add_or_update_repo sonarqube https://SonarSource.github.io/helm-chart-sonarqube
            add_or_update_repo ingress-nginx https://kubernetes.github.io/ingress-nginx
            add_or_update_repo sonatype https://sonatype.github.io/helm3-charts
            add_or_update_repo argo https://argoproj.github.io/argo-helm

            echo ""
            echo "Performing full Helm repository update..."
            helm repo update
            echo "✅ Helm repositories updated successfully"
          displayName: "Add Helm Repositories"

        # ================================
        # Deploy Nginx Ingress Controller
        # ================================
        - script: |
            echo "====================================="
            echo " Install Nginx Ingress Controller"
            echo "====================================="

            set -e
            export KUBECONFIG="$HOME/.kube/config"

            helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
              --namespace ingress-nginx \
              --create-namespace \
              --values ./$(HELM_WORKING_DIR)/nginx-ingress-controller/values.yaml \
              --wait \
              --timeout 15m

            echo "Waiting for LoadBalancer..."
            kubectl wait --namespace ingress-nginx \
              --for=condition=available deployment/ingress-nginx-controller \
              --timeout=600s

            kubectl get svc -n ingress-nginx
          displayName: "Deploy Nginx Ingress Controller"

        # ================================
        # Deploy ArgoCD
        # ================================
        - script: |
            echo "====================================="
            echo " Install ArgoCD"
            echo "====================================="

            set -e
            export KUBECONFIG="$HOME/.kube/config"

            helm upgrade --install argocd argo/argo-cd \
              --namespace argo \
              --create-namespace \
              --set server.service.type=ClusterIP \
              --wait \
              --timeout 15m

            kubectl apply -f ./$(HELM_WORKING_DIR)/argocd-ingress.yaml

            kubectl get pods -n argo
            kubectl get ingress -n argo
          displayName: "Deploy ArgoCD"

        # ================================
        # Deploy Vault
        # ================================
        - script: |
            echo "====================================="
            echo " Install Vault"
            echo "====================================="

            set -e
            export KUBECONFIG="$HOME/.kube/config"

            helm upgrade --install vault hashicorp/vault \
              --namespace vault \
              --create-namespace \
              --values ./$(HELM_WORKING_DIR)/vault/values.yaml \
              --wait \
              --timeout 15m

            kubectl apply -f ./$(HELM_WORKING_DIR)/vault-ingress.yaml

            kubectl get pods -n vault
            kubectl get ingress -n vault
          displayName: "Deploy Vault"

        # ================================
        # Deploy SonarQube
        # ================================
        - script: |
            echo "====================================="
            echo " Install SonarQube"
            echo "====================================="

            set -e
            export KUBECONFIG="$HOME/.kube/config"

            helm upgrade --install sonarqube sonarqube/sonarqube \
              --namespace sonarqube \
              --create-namespace \
              --values ./$(HELM_WORKING_DIR)/sonarqube/values.yaml \
              --wait \
              --timeout 20m

            kubectl apply -f ./$(HELM_WORKING_DIR)/sonarqube-ingress.yaml

            kubectl get pods -n sonarqube
            kubectl get ingress -n sonarqube
          displayName: "Deploy SonarQube"

        # ================================
        # Deploy Nexus
        # ================================
        - script: |
            echo "====================================="
            echo " Install Nexus Repository Manager"
            echo "====================================="

            set -e
            export KUBECONFIG="$HOME/.kube/config"

            helm upgrade --install nexus sonatype/nexus-repository-manager \
              --namespace nexus \
              --create-namespace \
              --values ./$(HELM_WORKING_DIR)/nexus/values.yaml \
              --wait \
              --timeout 20m

            kubectl apply -f ./$(HELM_WORKING_DIR)/nexus-ingress.yaml

            kubectl get pods -n nexus
            kubectl get pvc -n nexus
            kubectl get ingress -n nexus
          displayName: "Deploy Nexus"

        # ================================
        # Verify All Deployments
        # ================================
        - script: |
            echo "====================================="
            echo " Verify All Platform Deployments"
            echo "====================================="

            set -e
            export KUBECONFIG="$HOME/.kube/config"

            kubectl get ns

            echo "===== ingress-nginx ====="
            kubectl get pods -n ingress-nginx
            kubectl get svc -n ingress-nginx

            echo "===== ArgoCD ====="
            kubectl get pods -n argo
            kubectl get ingress -n argo

            echo "===== Vault ====="
            kubectl get pods -n vault
            kubectl get ingress -n vault

            echo "===== SonarQube ====="
            kubectl get pods -n sonarqube
            kubectl get ingress -n sonarqube

            echo "===== Nexus ====="
            kubectl get pods -n nexus
            kubectl get pvc -n nexus
            kubectl get ingress -n nexus

            echo "Platform deployment completed"
          displayName: "Verify All Platform Deployments"


# ================================
# Platform Cleanup Stage
# ================================
- stage: Platform_Cleanup
  displayName: "Platform Cleanup Stage"
  dependsOn: Platform_Deploy
  condition: and(succeeded(), eq(variables['RUN_CLEANUP'], 'true'))

  jobs:
    - job: CleanupPlatform
      displayName: "Cleanup Platform Components"
      timeoutInMinutes: 30
      cancelTimeoutInMinutes: 5

      workspace:
        clean: all

      steps:
        - checkout: self

        - task: HelmInstaller@1
          displayName: "Install Helm"
          inputs:
            helmVersionToInstall: "latest"

        - task: KubectlInstaller@0
          displayName: "Install kubectl"
          inputs:
            kubectlVersion: "latest"

        - script: |
            echo "====================================="
            echo " Configure kubeconfig for cleanup"
            echo "====================================="

            set -e

            mkdir -p $HOME/.kube

            aws eks update-kubeconfig \
              --region "$(AWS_DEFAULT_REGION)" \
              --name "$(CLUSTER_NAME)" \
              --kubeconfig "$HOME/.kube/config"

            export KUBECONFIG="$HOME/.kube/config"
            kubectl get nodes
          displayName: "Configure kubeconfig"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_SESSION_TOKEN: $(AWS_SESSION_TOKEN)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            echo "====================================="
            echo " Cleanup Helm Releases + Namespaces"
            echo "====================================="

            set +e
            export KUBECONFIG="$HOME/.kube/config"

            helm uninstall nexus -n nexus
            helm uninstall sonarqube -n sonarqube
            helm uninstall vault -n vault
            helm uninstall argocd -n argo
            helm uninstall ingress-nginx -n ingress-nginx

            kubectl delete namespace nexus --ignore-not-found=true
            kubectl delete namespace sonarqube --ignore-not-found=true
            kubectl delete namespace vault --ignore-not-found=true
            kubectl delete namespace argo --ignore-not-found=true
            kubectl delete namespace ingress-nginx --ignore-not-found=true

            echo " Cleanup done"
          displayName: "Cleanup Helm + Namespaces"
