# ============================================================================
# Azure DevOps CI Pipeline - Build, Scan & Push
# ============================================================================
# This pipeline builds Docker images, runs security scans, and pushes to ECR
# Author: DevOps Team
# Version: 2.1.0
# ============================================================================

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
  paths:
    include:
      - app/**
      - Dockerfile
      - .dockerignore
      - azure-ci-pipeline.yaml

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - app/**
      - Dockerfile
      - .dockerignore

pool:
  name: SelfHostedPool
  demands:
    - agent.os -equals Linux

# ================================
# Pipeline Variables
# ================================
variables:
  # AWS Configuration
  AWS_DEFAULT_REGION: "us-east-1"

  # Docker Configuration
  IMAGE_NAME: "nti-app"
  IMAGE_TAG: "$(Build.BuildId)"
  DOCKER_BUILDKIT: 1

  # Feature Flags
  RUN_SECURITY_SCAN: "true"
  RUN_UNIT_TESTS: "true"
  PUSH_TO_REGISTRY: "true"

  # Security Scan Configuration
  TRIVY_SEVERITY: "CRITICAL,HIGH"
  FAIL_ON_CRITICAL: "false"

# ================================
# Stages
# ================================
stages:

# ================================
# Build Stage
# ================================
- stage: Build
  displayName: "🔨 Build Stage"
  jobs:
    - job: ValidateAndBuild
      displayName: "Validate & Build Docker Image"
      timeoutInMinutes: 30

      steps:
        - checkout: self
          clean: true
          fetchDepth: 1

        - script: |
            echo "====================================="
            echo "  Pipeline Information"
            echo "====================================="
            echo "Build ID: $(Build.BuildId)"
            echo "Branch: $(Build.SourceBranchName)"
            echo "Commit: $(Build.SourceVersion)"
            echo "Agent: $(Agent.Name)"
            echo "====================================="
          displayName: "Pipeline Information"

        - script: |
            set -e
            echo "Validating AWS credentials..."

            if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
              echo "❌ AWS credentials not set!"
              exit 1
            fi

            aws sts get-caller-identity
            echo "✅ AWS credentials validated"
          displayName: "Validate AWS Credentials"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e
            echo "====================================="
            echo "  Get ECR Repository Details"
            echo "====================================="

            AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com"
            ECR_REPOSITORY="$ECR_REGISTRY/$(IMAGE_NAME)"

            echo "##vso[task.setvariable variable=AWS_ACCOUNT_ID]$AWS_ACCOUNT_ID"
            echo "##vso[task.setvariable variable=ECR_REGISTRY]$ECR_REGISTRY"
            echo "##vso[task.setvariable variable=ECR_REPOSITORY]$ECR_REPOSITORY"

            echo "AWS Account ID: $AWS_ACCOUNT_ID"
            echo "ECR Registry: $ECR_REGISTRY"
            echo "ECR Repository: $ECR_REPOSITORY"
            echo "Image Tag: $(IMAGE_TAG)"
          displayName: "Get ECR Details"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e
            echo "====================================="
            echo "  Login to Amazon ECR"
            echo "====================================="

            aws ecr get-login-password --region $(AWS_DEFAULT_REGION) | \
              docker login --username AWS --password-stdin $(ECR_REGISTRY)

            echo "✅ ECR login successful"
          displayName: "Login to ECR"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e
            echo "====================================="
            echo "  Lint Dockerfile"
            echo "====================================="

            if ! command -v hadolint &> /dev/null; then
              echo "Installing hadolint..."
              wget -qO /tmp/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
              chmod +x /tmp/hadolint
              HADOLINT=/tmp/hadolint
            else
              HADOLINT=hadolint
            fi

            if [ -f "Dockerfile" ]; then
              echo "Linting Dockerfile..."
              $HADOLINT Dockerfile || true
              echo "✅ Dockerfile lint completed"
            else
              echo "⚠️ No Dockerfile found"
            fi
          displayName: "Lint Dockerfile"
          continueOnError: true

        - script: |
            set -e
            echo "====================================="
            echo "  Cleanup Docker Space"
            echo "====================================="

            docker system prune -af || true
            docker builder prune -af || true
          displayName: "Cleanup Docker Space"
          continueOnError: true

        - script: |
            set -e
            echo "====================================="
            echo "  Build Docker Image"
            echo "====================================="

            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=$(git rev-parse --short HEAD)

            docker build \
              --network=host \
              --build-arg BUILD_DATE=$BUILD_DATE \
              --build-arg VCS_REF=$VCS_REF \
              --build-arg VERSION=$(IMAGE_TAG) \
              --label "org.opencontainers.image.created=$BUILD_DATE" \
              --label "org.opencontainers.image.revision=$VCS_REF" \
              --label "org.opencontainers.image.version=$(IMAGE_TAG)" \
              --label "org.opencontainers.image.source=$(Build.Repository.Uri)" \
              -t $(ECR_REPOSITORY):$(IMAGE_TAG) \
              -t $(ECR_REPOSITORY):latest \
              -t $(ECR_REPOSITORY):$(Build.SourceBranchName)-$(IMAGE_TAG) \
              -f Dockerfile \
              .

            echo ""
            echo "✅ Docker image built successfully"
            echo ""
            docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}" | grep "$(IMAGE_NAME)" || echo "Image list displayed above"
          displayName: "Build Docker Image"

        - script: |
            echo "====================================="
            echo "  Image Metadata"
            echo "====================================="

            echo "Image: $(ECR_REPOSITORY):$(IMAGE_TAG)"
            echo ""

            docker inspect $(ECR_REPOSITORY):$(IMAGE_TAG) --format='{{json .Config.Labels}}' | jq . || true

            echo ""
            echo "Image size:"
            docker images $(ECR_REPOSITORY):$(IMAGE_TAG) --format "{{.Size}}"
          displayName: "Show Image Metadata"

# ================================
# Security Scan Stage
# ================================
- stage: Security_Scan
  displayName: "🔒 Security Scan"
  dependsOn: Build
  condition: and(succeeded(), eq(variables['RUN_SECURITY_SCAN'], 'true'))

  jobs:
    - job: TrivyScan
      displayName: "Trivy Container Scan"
      timeoutInMinutes: 20

      steps:
        - checkout: self
          clean: true
          fetchDepth: 1

        - script: |
            set -e
            echo "====================================="
            echo "  Install Trivy Scanner"
            echo "====================================="

            if ! command -v trivy &> /dev/null; then
              mkdir -p $HOME/bin
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/bin
              export PATH=$HOME/bin:$PATH
              echo "##vso[task.prependpath]$HOME/bin"
            fi

            trivy --version
          displayName: "Install Trivy"

        - script: |
            set -e

            AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com"
            ECR_REPOSITORY="$ECR_REGISTRY/$(IMAGE_NAME)"

            aws ecr get-login-password --region $(AWS_DEFAULT_REGION) | \
              docker login --username AWS --password-stdin $ECR_REGISTRY

            echo "##vso[task.setvariable variable=ECR_REPOSITORY]$ECR_REPOSITORY"
          displayName: "Setup ECR Access"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e
            echo "====================================="
            echo "  Vulnerability Scan"
            echo "====================================="

            mkdir -p $(Build.ArtifactStagingDirectory)/security-reports

            trivy image \
              --format json \
              --output $(Build.ArtifactStagingDirectory)/security-reports/trivy-results.json \
              $(ECR_REPOSITORY):$(IMAGE_TAG)

            trivy image \
              --format table \
              --severity $(TRIVY_SEVERITY) \
              $(ECR_REPOSITORY):$(IMAGE_TAG)

            CRITICAL_COUNT=$(trivy image --format json $(ECR_REPOSITORY):$(IMAGE_TAG) | jq '[.Results[]?.Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length')
            HIGH_COUNT=$(trivy image --format json $(ECR_REPOSITORY):$(IMAGE_TAG) | jq '[.Results[]?.Vulnerabilities[]? | select(.Severity=="HIGH")] | length')

            echo ""
            echo "====================================="
            echo "  Vulnerability Summary"
            echo "====================================="
            echo "CRITICAL: $CRITICAL_COUNT"
            echo "HIGH: $HIGH_COUNT"

            if [ "$(FAIL_ON_CRITICAL)" = "true" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
              echo "❌ Critical vulnerabilities found! Failing build."
              exit 1
            fi

            echo "✅ Security scan completed"
          displayName: "Run Trivy Scan"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - task: PublishBuildArtifacts@1
          displayName: "Publish Security Reports"
          inputs:
            PathtoPublish: "$(Build.ArtifactStagingDirectory)/security-reports"
            ArtifactName: "security-reports"
            publishLocation: "Container"

# ================================
# Push Stage
# ================================
- stage: Push
  displayName: "📤 Push to Registry"
  dependsOn:
    - Build
    - Security_Scan
  condition: |
    and(
      succeeded('Build'),
      or(succeeded('Security_Scan'), eq(variables['RUN_SECURITY_SCAN'], 'false')),
      eq(variables['PUSH_TO_REGISTRY'], 'true'),
      or(
        eq(variables['Build.SourceBranch'], 'refs/heads/main'),
        eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
        eq(variables['Build.Reason'], 'Manual')
      )
    )

  jobs:
    - job: PushImage
      displayName: "Push Docker Image to ECR"
      timeoutInMinutes: 30

      steps:
        - checkout: self
          clean: true
          fetchDepth: 1

        - script: |
            set -e

            AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$(AWS_DEFAULT_REGION).amazonaws.com"
            ECR_REPOSITORY="$ECR_REGISTRY/$(IMAGE_NAME)"

            echo "##vso[task.setvariable variable=ECR_REGISTRY]$ECR_REGISTRY"
            echo "##vso[task.setvariable variable=ECR_REPOSITORY]$ECR_REPOSITORY"

            aws ecr get-login-password --region $(AWS_DEFAULT_REGION) | \
              docker login --username AWS --password-stdin $ECR_REGISTRY
          displayName: "Login to ECR"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        # ============================================================
        # FIX ADDED HERE: Auto Create Repository If Not Exists
        # ============================================================
        - script: |
            set -e
            echo "====================================="
            echo "  Ensure ECR Repository Exists"
            echo "====================================="

            if aws ecr describe-repositories --repository-names $(IMAGE_NAME) --region $(AWS_DEFAULT_REGION) >/dev/null 2>&1; then
              echo "✅ Repository $(IMAGE_NAME) already exists"
            else
              echo "⚠️ Repository $(IMAGE_NAME) not found. Creating it now..."
              aws ecr create-repository --repository-name $(IMAGE_NAME) --region $(AWS_DEFAULT_REGION)
              echo "✅ Repository $(IMAGE_NAME) created successfully"
            fi
          displayName: "Ensure ECR Repository Exists"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

        - script: |
            set -e

            echo "====================================="
            echo "  Push Docker Image to ECR (Retry Enabled)"
            echo "====================================="

            export DOCKER_CLIENT_TIMEOUT=600
            export COMPOSE_HTTP_TIMEOUT=600

            retry_push() {
              local image=$1
              local retries=5
              local wait_time=10

              for i in $(seq 1 $retries); do
                echo ""
                echo "Attempt $i/$retries: docker push $image"

                if docker push "$image"; then
                  echo "✅ Push succeeded: $image"
                  return 0
                fi

                echo "❌ Push failed: $image"
                echo "Waiting $wait_time seconds before retry..."
                sleep $wait_time
                wait_time=$((wait_time * 2))
              done

              echo "🔥 Push failed after $retries attempts: $image"
              return 1
            }

            echo "Pushing main tag..."
            retry_push "$(ECR_REPOSITORY):$(IMAGE_TAG)"

            echo "Pushing latest tag..."
            docker tag "$(ECR_REPOSITORY):$(IMAGE_TAG)" "$(ECR_REPOSITORY):latest"
            retry_push "$(ECR_REPOSITORY):latest"

            echo "Pushing branch tag..."
            BRANCH_TAG="$(Build.SourceBranchName)-$(IMAGE_TAG)"
            docker tag "$(ECR_REPOSITORY):$(IMAGE_TAG)" "$(ECR_REPOSITORY):$BRANCH_TAG"
            retry_push "$(ECR_REPOSITORY):$BRANCH_TAG" || true

            echo ""
            echo "✅ All pushes completed"
          displayName: "Push Docker Image to ECR (Retry)"

        - script: |
            echo "====================================="
            echo "  Verify Pushed Images"
            echo "====================================="

            aws ecr describe-images \
              --repository-name $(IMAGE_NAME) \
              --region $(AWS_DEFAULT_REGION) \
              --query 'imageDetails[?imageTags!=`null`] | sort_by(@, &imagePushedAt) | [-5:].{Tags:imageTags,Pushed:imagePushedAt,Size:imageSizeInBytes}' \
              --output table

            if aws ecr describe-images \
              --repository-name $(IMAGE_NAME) \
              --region $(AWS_DEFAULT_REGION) \
              --image-ids imageTag=$(IMAGE_TAG) &>/dev/null; then
              echo "✅ Image with tag $(IMAGE_TAG) verified in ECR"
            else
              echo "⚠️ Could not verify image tag $(IMAGE_TAG)"
            fi
          displayName: "Verify Pushed Images"
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

# ================================
# Notify Stage
# ================================
- stage: Notify
  displayName: "📢 Notify"
  dependsOn:
    - Build
    - Security_Scan
    - Push
  condition: always()

  jobs:
    - job: BuildSummary
      displayName: "Build Summary"

      steps:
        - script: |
            echo "====================================="
            echo "  CI Pipeline Summary"
            echo "====================================="
            echo ""
            echo "Build ID: $(Build.BuildId)"
            echo "Branch: $(Build.SourceBranchName)"
            echo "Commit: $(Build.SourceVersion)"
            echo "Image Tag: $(IMAGE_TAG)"
            echo ""
            echo "====================================="
            echo "  Stage Results"
            echo "====================================="
            echo "Build Stage: Completed"
            echo "Security Scan Enabled: $(RUN_SECURITY_SCAN)"
            echo "Push Enabled: $(PUSH_TO_REGISTRY)"
            echo ""
            echo "✅ CI Pipeline completed"
          displayName: "Print Build Summary"
