trigger:
  branches:
    include:
      - main

pool:
  name: SelfHostedPool


variables:
  TF_WORKING_DIR: "terraform"
  AWS_DEFAULT_REGION: "us-east-1"
  RUN_DESTROY: "false"

stages:
  - stage: Terraform_Apply
    displayName: "Terraform Apply Stage"
    jobs:
      - job: Apply
        displayName: "Terraform Apply"
        steps:
          - checkout: self

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
              unzip terraform_1.6.6_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Install Terraform"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform init
            displayName: "Terraform Init"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform validate
            displayName: "Terraform Validate"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform plan -var-file=nonprod.tfvars
            displayName: "Terraform Plan"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform apply -var-file=nonprod.tfvars -auto-approve
            displayName: "Terraform Apply"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform output
            displayName: "Terraform Outputs"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: Terraform_Destroy
    displayName: "Terraform Destroy Stage (Manual)"
    dependsOn: Terraform_Apply
    condition: and(succeeded(), eq(variables['RUN_DESTROY'], 'true'))

    jobs:
      - job: Destroy
        displayName: "Terraform Destroy"
        steps:
          - checkout: self

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
              unzip terraform_1.6.6_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Install Terraform"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform init
            displayName: "Terraform Init"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              cd $(TF_WORKING_DIR)
              terraform destroy -var-file=nonprod.tfvars -auto-approve
            displayName: "Terraform Destroy"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
